import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import Providers from "@/lib/providers";
//import openWS from "@/lib/finnhub-websocket";
import "@/lib/finnhub-websocket";

//openWS();

const geistSans = GeistSans;
const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
